# Workflow name displayed in GitHub Actions
name: variables

# Global environment variables (available to all jobs and steps)
env:
  Cloud: AWS

# Event that triggers the workflow
on:
  workflow_dispatch:

# Collection of jobs
jobs:

  # First job name
  greeting_job:

    # Runner machine on which the job executes
    runs-on: ubuntu-latest

    # Job-level environment variable
    env:
      Greeting: Hello

    # Steps executed sequentially
    steps:

      # Step name displayed in Actions UI
      - name: Say Hello to Gandhi

        # Step-level environment variable
        # Available only within this step
        env:
          FullName: Barnana Gandhi

        # Execute shell command PROJECT_NAME set on the settings-> secrate-> actions
        run: echo "$Greeting $FullName Deploy ${{ vars.PROJECT_NAME }} on the $Cloud platform"
