name: Context varibale
on: 
  workflow_dispatch:
env:
  surname: Barnana

jobs:
  welcome_job:
    runs-on: ubuntu-latest
    env:
      fname: Gandhi
    steps:
      - name: Conext variable
      run: |
        echo "Repository ${{github.repository}}"
        echo "super env $${{env.surname}}"
        echo "Actor ${{github.actor}}"
        echo "Hello"
    
  
