name: context-variable
on:
  workflow_dispatch:
env:
  key-text: AWS
jobs:
  text-context-variables:
    runs-on: ubuntu-latest
    steps:
      - name: checking context variable
        run: |
        echo "${{env.key-text}} git hub Repo name ${{github.repository}}"
        echo " Git hub branch ${{github.ref_name}}"
        echo " Git hub Work flow ${{github.workflow}}"
