name: Dropdown variable
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Select the Option"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
jobs:
  dropdown:
    runs-on: ubuntu-latest
    steps:
      - name: check the options
        run: echo "Select environment $${{inputs.env}}"
