name: secrets

on:
  workflow_dispatch:
  push:
    branches: [ "main"]
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: maven version
      run: mvn -version
     
    - name: check secrets
      run: echo "Hello gandhi  secret is ${{secrets.DEV_URL_PRACT}}"

    
  
