name: use Upload artifact 
on:
  push:

jobs:
  build_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: |
          echo " Hello artifact demo  download the file" >> EFO
          echo " File created successfully"
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: "artifact demo"
          path: . 

