name: env single workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  key: gandhi

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: maven version check
        run : mvn -version

      - name: check master env
        run : Hello ${{env.key}} .
